"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /mpfs2 ".\WebPages2" "." "MPFSImg2.bin"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /mpfs2 /C18 ".\WebPages2" "." "MPFSImg2.c"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /mpfs2 /ASM30 ".\WebPages2" "." "MPFSImg2.s"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /classic ".\WebPages" "." "MPFSImg.bin"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /classic /C18 ".\WebPages" "." "MPFSImg.c"
"..\Microchip\TCPIP Stack\Utilities\MPFS2.exe" /classic /ASM30 ".\WebPages" "." "MPFSImg.s"