<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>深圳市精锐达网络控制卡 TCP/IP 网页控制应用</title>
<link href="/mchp.css" rel="stylesheet" type="text/css" />
<script src="/mchp.js" type="text/javascript"></script>
</head>

<body>
<div id="shadow-one"><div id="shadow-two"><div id="shadow-three"><div id="shadow-four">
<div id="page">

<div style="padding:0 0 5px 5px"><img src="/szjrd.gif" alt="SZJRD" /></div>

<div id="title"><div class="right">以太网控制卡服务器</div><span id="hello">&nbsp;</span></div>

<div id="menu">
<a href="/index.htm">简要</a>
<!--<a href="/dynvars.htm">动态变量</a>-->
<a href="/forms.htm">输出控制</a>
<!--<a href="/auth.htm">Authentication</a>-->
<!--<a href="/cookies.htm">Cookies</a>-->
<!--<a href="/upload.htm">File Uploads</a>-->
<a href="/email">发送 E-mail</a>
<a href="/dyndns">动态DNS</a>
<a href="/protect/config.htm">配置</a>
</div>